package.json, src/containers/Profile/Profile.stories.js, src/containers/Profile/Profile.storyData.js, src/containers/Profile/components/Main/Main.js, src/containers/Profile/components/Main/Occupations.js
https://thewing.atlassian.net/browse/MO-470
=> [MO 446] multiple occupations

.storybook/config.js, README.md, package.json, src/assets/img/arrow.svg, src/breakpoints.js, src/style/normalize.scss, src/theme.js, src/ui/Carousel/Carousel.js, src/ui/Carousel/Carousel.stories.js, webpack/production.config.js, yarn.lock
Add carousel component (responsive)
[MO-236](https://thewing.atlassian.net/browse/MO-236)
1. Go to carousel story
2. Visit default
3. Click "Viewport" in addons tab (you'll see "Action logger" and "Viewport")
4. Make sure that carousel looks correct on all screen sizes
5. Repeat for "1 slide" story
=> Mo 236/carousel

package.json, src/index.js, src/ui/Card/Card.js, src/ui/Card/Card.stories.js
Creating card template for use in MO-237 (next step will be actually using it in members portal)
Just a part of [MO-237](https://thewing.atlassian.net/browse/MO-237)
=> Create card for use in MO-237

package.json, src/index.js
Exporting Carousel for use
None
=> Export Carousel

package.json, src/containers/Profile/components/AdditionalInfo/AdditionalInfo.js
- Move email to the last position
- https://thewing.atlassian.net/browse/MO-465
Please delete this if not relevant.
1. go to profile
2. scroll down
=> MO-465 - Profile: contact email should be the last feature

package.json, src/containers/Profile/Profile.js, src/containers/Profile/components/EditForm.js, src/utils.js
Fix the amount of days according the to selected month
- https://thewing.atlassian.net/browse/MO-474
Please delete this if not relevant.
- go to profile (edit) and scroll to birthday section
- select an invalid date . Ex. Feb 31
=> MO-474 - Profile: birthday invalid dates

package.json, src/ui/ListItem/ListItem.js
- Remove 'as' property from Box element
- https://thewing.atlassian.net/browse/MO-492
Please delete this if not relevant.
1. Go to profile and scroll down
=> MO-492 Profile footer fields and icons are misaligned

package.json, src/ui/Carousel/Carousel.js, src/ui/Carousel/Carousel.stories.js
Remove unnecessary margins on carousel
[MO-238](https://thewing.atlassian.net/browse/MO-238)
=> [MO-238] Remove unnecessary margins on carousel

package.json, src/containers/Profile/components/AdditionalInfo/AdditionalInfo.js, src/containers/Profile/components/ControlBar.js, src/containers/Profile/components/Head/Head.js, src/containers/Profile/components/Main/ChipList.js, src/containers/Profile/components/Main/Main.js, src/ui/Chip/Chip.js, src/ui/Drawer/Drawer.js, src/ui/Drawer/Drawer.stories.js, yarn.lock
- Update React-Spring node module
- Fix Drawer exit transition
- Add ability to click on backdrop of drawer to exit it
[MO-500](https://thewing.atlassian.net/browse/MO-500)
=> [MO-500] Update react-spring

package.json, src/index.js, src/ui/Message/Message.js, src/ui/Page/Page.js, src/ui/Page/Page.stories.js
We needed to pull out the Page component!
[MO-151](https://thewing.atlassian.net/browse/MO-151)
1. Go to the Page story
2. Confirm all styles look right in each story on all devices
=> [MO-151] Add Page component

package.json, src/index.js
- Add ErrorLoading to the global export
- https://github.com/the-wing/members-portal/pull/336
=> MO-421:  Error handling for list views

package.json, src/ui/Page/Page.js
Tweaking the height of the header on Page component
https://thewing.atlassian.net/browse/MO-151
=> [MO-151] Tweak Page Header styles

package.json, src/index.js
=> Export all components for use

package.json, src/index.js, src/ui/Loading/Circle.js, src/ui/Loading/Circle.stories.js, src/ui/Loading/TextRow.js, src/ui/Loading/TextRow.stories.js
To match designs, alter loading state components' colors/opacity
=> [MO-158] Alter loading state color

package.json, src/ui/Filters/FilterOption.js, src/ui/Filters/Filters.js, src/ui/Filters/Filters.stories.js, src/ui/Filters/Option.js
Please enter a short description of this PR.
=> Filters component 

package.json, src/index.js
=> Export filters - the right way

package.json, src/ui/ListItem/ListItem.js, src/ui/ListItem/ListItem.stories.js
The inner content of a ListItem should span the entire width of the item.
Needed for: https://thewing.atlassian.net/browse/MO-158
=> [MO-158] Fix up ListItem style

package.json, src/ui/Filters/Filters.js
Increased width for filters title to ensure it stays on one line.
=> Filters title tweak

package.json, src/ui/Carousel/Carousel.js, src/ui/Carousel/Carousel.stories.js, src/ui/Forms/Select/SearchableSingleValue.js, src/ui/Forms/Select/Select.js
This introduced some issues with styling. Reverting for now.
Was for https://thewing.atlassian.net/browse/MO-499
=> Revert carousel tweaks

package.json, src/index.js, src/ui/VideoPlayer/VideoPlayer.js, src/ui/VideoPlayer/VideoPlayer.stories.js, yarn.lock
Video Player added
https://thewing.atlassian.net/browse/PAMS-1950
=> PAMS-1950 Video Player redone, lock included
